name: project_vol10
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.4+2
  firebase_analytics: ^5.0.11
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  geolocator: ^5.3.1
  uuid: ^2.0.4
  image: ^2.1.12
  animator: ^1.0.0+5
  cupertino_icons: ^0.1.3
  path_provider: ^1.6.5
  firebase_messaging: ^6.0.13
  timeago: ^2.0.26 
  cached_network_image: ^2.0.0
  flutter_svg: ^0.17.4
  flutter_bloc: ^2.1.1
  groovin_material_icons:
  http: ^0.12.0+2
  firebase_dynamic_links: ^0.5.0+1
  rxdart: ^0.22.1+1
  flutter_secure_storage: ^3.2.1+1
  country_code_picker: ^1.1.7
  pin_view: ^1.0.1
  firebase_core: ^0.4.4+3
  intl: ^0.16.1
  flutter_datetime_picker: 
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git
  autocomplete_textfield: ^1.7.3
  dash_chat: ^1.0.19
  material_design_icons_flutter: ^4.0.5145
  file_picker: ^1.4.2
  flutter_email_sender: ^3.0.1
  share: ^0.6.4+3
  shared_preferences: ^0.5.6+3
  imagebutton: ^0.0.6
  flutter_rounded_date_picker: ^1.0.4
  datetime_picker_formfield: ^1.0.0
  font_awesome_flutter: ^8.8.1
  geocoder: ^0.2.1
  location: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
     - assets/insta_logo.png
     - assets/google_icon.jpg
     - assets/no_image.png
     - assets/blankimage.png
  